name: C++ Cross-Platform Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        mode: ["Debug", "Release"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        shell: bash
        run: ./configure ${{ matrix.mode }} -Werror

      - name: Build
        shell: bash
        run: ./CI/compile ${{ matrix.mode }}
