name: C++ Unit Tests

on: push

jobs:
  tests:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        shell: bash
        run: ./configure Tests

      - name: Build
        shell: bash
        run: ./CI/compile Tests

      - name: Run tests
        shell: bash
        run: ./build/Tests/RayTracerTests --verbose -j1 -S --timeout 30
